//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zengo.WP8.FAS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zengo.WP8.FAS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my account.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is validated.
        /// </summary>
        public static string AccountValidated {
            get {
                return ResourceManager.GetString("AccountValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string ActivatePageTitle {
            get {
                return ResourceManager.GetString("ActivatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of your account is complete.
        /// </summary>
        public static string ActivationCompleted {
            get {
                return ResourceManager.GetString("ActivationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Api Changes Received.
        /// </summary>
        public static string APIUpdates {
            get {
                return ResourceManager.GetString("APIUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate.
        /// </summary>
        public static string AppBarActivate {
            get {
                return ResourceManager.GetString("AppBarActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        public static string AppBarGoBack {
            get {
                return ResourceManager.GetString("AppBarGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string AppBarHelp {
            get {
                return ResourceManager.GetString("AppBarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string AppBarHistory {
            get {
                return ResourceManager.GetString("AppBarHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string AppBarLanguage {
            get {
                return ResourceManager.GetString("AppBarLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string AppBarLogin {
            get {
                return ResourceManager.GetString("AppBarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string AppBarRegister {
            get {
                return ResourceManager.GetString("AppBarRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset password.
        /// </summary>
        public static string AppBarResetPassword {
            get {
                return ResourceManager.GetString("AppBarResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarSearch {
            get {
                return ResourceManager.GetString("AppBarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win.
        /// </summary>
        public static string AppBarShop {
            get {
                return ResourceManager.GetString("AppBarShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort ascending.
        /// </summary>
        public static string AppBarSortAscending {
            get {
                return ResourceManager.GetString("AppBarSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort descending.
        /// </summary>
        public static string AppBarSortDescending {
            get {
                return ResourceManager.GetString("AppBarSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string AppBarSubmit {
            get {
                return ResourceManager.GetString("AppBarSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update password.
        /// </summary>
        public static string AppBarUpdatePassword {
            get {
                return ResourceManager.GetString("AppBarUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates - please wait.
        /// </summary>
        public static string ApplyUpdates {
            get {
                return ResourceManager.GetString("ApplyUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Votes.
        /// </summary>
        public static string BuyVotesPage {
            get {
                return ResourceManager.GetString("BuyVotesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Club.
        /// </summary>
        public static string ByClubTitle {
            get {
                return ResourceManager.GetString("ByClubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Country.
        /// </summary>
        public static string ByCountryTitle {
            get {
                return ResourceManager.GetString("ByCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Name.
        /// </summary>
        public static string ByNameTitle {
            get {
                return ResourceManager.GetString("ByNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Position.
        /// </summary>
        public static string ByPositionTitle {
            get {
                return ResourceManager.GetString("ByPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Vote.
        /// </summary>
        public static string CastingVote {
            get {
                return ResourceManager.GetString("CastingVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Vote.
        /// </summary>
        public static string CastVoteButton {
            get {
                return ResourceManager.GetString("CastVoteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre Back.
        /// </summary>
        public static string CentreBackName {
            get {
                return ResourceManager.GetString("CentreBackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change my password.
        /// </summary>
        public static string ChangeMyPassword {
            get {
                return ResourceManager.GetString("ChangeMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Password.
        /// </summary>
        public static string ChangingPassword {
            get {
                return ResourceManager.GetString("ChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm your email address.
        /// </summary>
        public static string ConfirmEmailWatermark {
            get {
                return ResourceManager.GetString("ConfirmEmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm your new password.
        /// </summary>
        public static string ConfirmNewPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm your password.
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you play football?.
        /// </summary>
        public static string DoYouPlayFootball {
            get {
                return ResourceManager.GetString("DoYouPlayFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email address.
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        public static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a new password.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the pin we emailed.
        /// </summary>
        public static string EnterPinFromEmail {
            get {
                return ResourceManager.GetString("EnterPinFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the pin we emailed to you to activate your account.
        /// </summary>
        public static string EnterPinInstruction {
            get {
                return ResourceManager.GetString("EnterPinInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your pin.
        /// </summary>
        public static string EnterPinWatermark {
            get {
                return ResourceManager.GetString("EnterPinWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        public static string EuropeAbriviation {
            get {
                return ResourceManager.GetString("EuropeAbriviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string EuropeName {
            get {
                return ResourceManager.GetString("EuropeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your existing password.
        /// </summary>
        public static string ExistingPasswordWatermark {
            get {
                return ResourceManager.GetString("ExistingPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Fans All Star Global Vote?.
        /// </summary>
        public static string FAQ1 {
            get {
                return ResourceManager.GetString("FAQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you select the initial shortlist of 1,100 players?.
        /// </summary>
        public static string FAQ10 {
            get {
                return ResourceManager.GetString("FAQ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAS’ panel of football experts have selected 1,100 of the best players from Europe and the Rest of the World..
        /// </summary>
        public static string FAQ11 {
            get {
                return ResourceManager.GetString("FAQ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can participate?.
        /// </summary>
        public static string FAQ12 {
            get {
                return ResourceManager.GetString("FAQ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone in the world who has either downloaded the Fans All Star application or registered at www.fansallstar.com. If you are aged under eighteen (18) you will need to obtain the consent of your parent or guardian..
        /// </summary>
        public static string FAQ13 {
            get {
                return ResourceManager.GetString("FAQ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I have more than one login?.
        /// </summary>
        public static string FAQ14 {
            get {
                return ResourceManager.GetString("FAQ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Only one login is allowed per participant..
        /// </summary>
        public static string FAQ15 {
            get {
                return ResourceManager.GetString("FAQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you decide the position where a player is allocated if he plays in many different positions for his club?.
        /// </summary>
        public static string FAQ16 {
            get {
                return ResourceManager.GetString("FAQ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of conflict, the FAS panel of football experts have selected player positions based on a number of factors including a) most frequent position for his club and b) the player’s favourite position. Current default position for any single player in the 1,100 player shortlist is final and will not be subject to change under any circumstances..
        /// </summary>
        public static string FAQ17 {
            get {
                return ResourceManager.GetString("FAQ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if a Rest of the World player acquires a European nationality or vice versa? .
        /// </summary>
        public static string FAQ18 {
            get {
                return ResourceManager.GetString("FAQ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players are assigned a nationality based on the nation they are eligible to represent. In the case of a player with dual nationality and no international caps, he will be assigned his nationality of birth..
        /// </summary>
        public static string FAQ19 {
            get {
                return ResourceManager.GetString("FAQ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered participants in the Fans All Star Global Vote 2013 will be able to select their favourite European and Rest of the World  squads (two starting elevens plus 4 substitutes on each squad making a total of 30 players). All participants who register in the Fans All Star Global Vote 2013 will also be automatically entered into a free prize draw. Entry into the Fans All Star Global Vote is free. See below for further details..
        /// </summary>
        public static string FAQ2 {
            get {
                return ResourceManager.GetString("FAQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS ALL STAR GLOBAL VOTE.
        /// </summary>
        public static string FAQ20 {
            get {
                return ResourceManager.GetString("FAQ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are the final squads selected for the Fans All Stars Global Vote?.
        /// </summary>
        public static string FAQ21 {
            get {
                return ResourceManager.GetString("FAQ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final squads of 15 will comprise those players that have received the highest amount of votes in each position. .
        /// </summary>
        public static string FAQ22 {
            get {
                return ResourceManager.GetString("FAQ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first eleven for both squads will be:-.
        /// </summary>
        public static string FAQ23 {
            get {
                return ResourceManager.GetString("FAQ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goalkeeper with the highest amount of votes.
        /// </summary>
        public static string FAQ24 {
            get {
                return ResourceManager.GetString("FAQ24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right back with the highest amount of votes.
        /// </summary>
        public static string FAQ25 {
            get {
                return ResourceManager.GetString("FAQ25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left back with the highest amount of votes.
        /// </summary>
        public static string FAQ26 {
            get {
                return ResourceManager.GetString("FAQ26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two centre backs with the 
        ///highest amount of votes.
        /// </summary>
        public static string FAQ27 {
            get {
                return ResourceManager.GetString("FAQ27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The four midfielders with the 
        ///highest amount of votes.
        /// </summary>
        public static string FAQ28 {
            get {
                return ResourceManager.GetString("FAQ28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two forwards with the highest amount of votes.
        /// </summary>
        public static string FAQ29 {
            get {
                return ResourceManager.GetString("FAQ29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Fans All Star Prize Competition 2013?.
        /// </summary>
        public static string FAQ3 {
            get {
                return ResourceManager.GetString("FAQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The substitutes for both squads will be.
        /// </summary>
        public static string FAQ30 {
            get {
                return ResourceManager.GetString("FAQ30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goalkeeper with the second 
        ///highest amount of votes.
        /// </summary>
        public static string FAQ31 {
            get {
                return ResourceManager.GetString("FAQ31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The centre back with the third 
        ///highest amount of votes.
        /// </summary>
        public static string FAQ32 {
            get {
                return ResourceManager.GetString("FAQ32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The midfielder with the fifth 
        ///highest amount of votes.
        /// </summary>
        public static string FAQ33 {
            get {
                return ResourceManager.GetString("FAQ33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forward with the third highest amount of votes.
        /// </summary>
        public static string FAQ34 {
            get {
                return ResourceManager.GetString("FAQ34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see the Terms &amp; Conditions for further details..
        /// </summary>
        public static string FAQ35 {
            get {
                return ResourceManager.GetString("FAQ35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the voting period?.
        /// </summary>
        public static string FAQ36 {
            get {
                return ResourceManager.GetString("FAQ36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting starts at 23.59 BST on Friday 7 June 2013 and closes on Saturday 31 August 2013 at 23.59 BST. Voting will be divided into 3 voting periods:.
        /// </summary>
        public static string FAQ37 {
            get {
                return ResourceManager.GetString("FAQ37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Voting Period - commences at 23.59 BST on Friday 7 June 2013 and closes at 23.59 BST on Sunday 30 June 2013.
        /// </summary>
        public static string FAQ38 {
            get {
                return ResourceManager.GetString("FAQ38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Voting Period - commences at 00.01 BST on Monday 1 July 2013 and closes at 23.59 BST on Wednesday 31 July 2013.
        /// </summary>
        public static string FAQ39 {
            get {
                return ResourceManager.GetString("FAQ39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered participants in the Fans All Star Global Vote 2013 will also have the opportunity to enter our prize competition which requires participants to select their a European and a Rest of the World  squads (two starting elevens plus 4 substitutes on each squad making a total of 30 players) that they think our panel of experts will determine to be the best 15-man European squad and the 15-man Rest of the World squad. There is a paid for entry route and free entry route into the competition. See below fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FAQ4 {
            get {
                return ResourceManager.GetString("FAQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Voting Period - commences at 00.01 BST on Thursday 1 August 2013 and closes at 23.59 BST on Saturday 31 August 2013.
        /// </summary>
        public static string FAQ40 {
            get {
                return ResourceManager.GetString("FAQ40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I register and submit my squads? .
        /// </summary>
        public static string FAQ41 {
            get {
                return ResourceManager.GetString("FAQ41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can register and vote online at www.fansallstar.com, via the FAS app or on our Facebook page and submit your free European and ROTW squads. .
        /// </summary>
        public static string FAQ42 {
            get {
                return ResourceManager.GetString("FAQ42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any elimination rounds removing players from this shortlist during the duration of the global vote? .
        /// </summary>
        public static string FAQ43 {
            get {
                return ResourceManager.GetString("FAQ43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will also be two elimination rounds reducing the list of players available to vote for:.
        /// </summary>
        public static string FAQ44 {
            get {
                return ResourceManager.GetString("FAQ44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after the First Voting Period the list of players will be reduced from 1,100 players to the 660 players who received the highest votes between  (330 Europe and 330 ROTW comprising of the 60 goalkeepers, 60 right backs, 60 left backs, 120 centre backs, 240 midfielders and 120 forwards); and .
        /// </summary>
        public static string FAQ45 {
            get {
                return ResourceManager.GetString("FAQ45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after the Second Voting Period the list of players will be reduced from 660 players to the 110 players who received the highest votes between  (55 Europe and 55 ROTW comprising of the 10 goalkeepers, 10 right backs, 10 left backs, 20  centre backs, 40 midfielders and 20 forwards)..
        /// </summary>
        public static string FAQ46 {
            get {
                return ResourceManager.GetString("FAQ46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final squad selections will be announced on 3 September 2013..
        /// </summary>
        public static string FAQ47 {
            get {
                return ResourceManager.GetString("FAQ47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any new players be added to this shortlist during the duration of the Fans All Star Global Vote 2013? .
        /// </summary>
        public static string FAQ48 {
            get {
                return ResourceManager.GetString("FAQ48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players will be added to this shortlist during the Fans All Star Global Vote 2013. .
        /// </summary>
        public static string FAQ49 {
            get {
                return ResourceManager.GetString("FAQ49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many players can I choose from?.
        /// </summary>
        public static string FAQ5 {
            get {
                return ResourceManager.GetString("FAQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any selection limitations? .
        /// </summary>
        public static string FAQ50 {
            get {
                return ResourceManager.GetString("FAQ50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no country, league or team limitations. Voters are free to select any player from the shortlists during each of the Voting Periods. Please note that players will be reduced in each of the second and third voting rounds..
        /// </summary>
        public static string FAQ51 {
            get {
                return ResourceManager.GetString("FAQ51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times can I vote?.
        /// </summary>
        public static string FAQ52 {
            get {
                return ResourceManager.GetString("FAQ52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a registered participant, you can only vote once. .
        /// </summary>
        public static string FAQ53 {
            get {
                return ResourceManager.GetString("FAQ53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are the voting stats updated?.
        /// </summary>
        public static string FAQ54 {
            get {
                return ResourceManager.GetString("FAQ54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAS may in its sole discretion display the absolute total number of registered votes but no specific data will be provided for single players..
        /// </summary>
        public static string FAQ55 {
            get {
                return ResourceManager.GetString("FAQ55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I always have to submit one or two full squads?.
        /// </summary>
        public static string FAQ56 {
            get {
                return ResourceManager.GetString("FAQ56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants must submit two squads..
        /// </summary>
        public static string FAQ57 {
            get {
                return ResourceManager.GetString("FAQ57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any prizes?.
        /// </summary>
        public static string FAQ58 {
            get {
                return ResourceManager.GetString("FAQ58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. By submitting a valid vote, you will automatically be entered into the Free Prize Draw. The Free Prize Draw will be divided into three 3 periods with a total of 10 framed football shirts signed by current and past football legends (please see Terms &amp; Conditions for more details)..
        /// </summary>
        public static string FAQ59 {
            get {
                return ResourceManager.GetString("FAQ59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants will select their players from a shortlist of 1,100 players (550 from Europe and 550 from the Rest Of The World) from 265 different clubs, 93 countries and 55 leagues around the world..
        /// </summary>
        public static string FAQ6 {
            get {
                return ResourceManager.GetString("FAQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS ALL STAR PRIZE COMPETITION.
        /// </summary>
        public static string FAQ60 {
            get {
                return ResourceManager.GetString("FAQ60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the winning prize?.
        /// </summary>
        public static string FAQ61 {
            get {
                return ResourceManager.GetString("FAQ61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cash prize of £50,000 will be paid to the winner..
        /// </summary>
        public static string FAQ62 {
            get {
                return ResourceManager.GetString("FAQ62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will the winner be chosen?.
        /// </summary>
        public static string FAQ63 {
            get {
                return ResourceManager.GetString("FAQ63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winner will be the entrant that correctly predicts both the 15-man European squad and the 15-man Rest of the World squad chosen by a panel of international football experts.  If more than one participant correctly predicts both squads then one winner will be selected by an independently adjudicated random selection after the end of the Promotion Period. The Cash prize is only available to Adults aged 18+..
        /// </summary>
        public static string FAQ64 {
            get {
                return ResourceManager.GetString("FAQ64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the entry period?.
        /// </summary>
        public static string FAQ65 {
            get {
                return ResourceManager.GetString("FAQ65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prize competition opens at 23.59 BST on Friday 7 June 2013 and closes on Saturday 31 August 2013 at 23.59 BST..
        /// </summary>
        public static string FAQ66 {
            get {
                return ResourceManager.GetString("FAQ66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times can I enter?.
        /// </summary>
        public static string FAQ67 {
            get {
                return ResourceManager.GetString("FAQ67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a registered participant, you can enter as many times as you wish using your account. You can either enter for Free by completing a short questionnaire or you can pay to enter. Entries are priced in bundles of 30 votes (required to submit two squads in each entry) at a cost of US$1.00 (one US dollar)..
        /// </summary>
        public static string FAQ68 {
            get {
                return ResourceManager.GetString("FAQ68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I always have to submit one or two full squads?.
        /// </summary>
        public static string FAQ69 {
            get {
                return ResourceManager.GetString("FAQ69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 550 players for each squad are made up by 50 goalkeepers, 50 right backs, 50 left backs, 100 centre backs, 200 midfielders and 100 forwards..
        /// </summary>
        public static string FAQ7 {
            get {
                return ResourceManager.GetString("FAQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants must submit two full squads in each entry. Participants can submit a maximum of 30 entries per person..
        /// </summary>
        public static string FAQ70 {
            get {
                return ResourceManager.GetString("FAQ70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I enter and submit my squads? .
        /// </summary>
        public static string FAQ71 {
            get {
                return ResourceManager.GetString("FAQ71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter via your fans all star account online at www.fansallstar.com, via the FAS app or Facebook and submit your free European and ROTW squads..
        /// </summary>
        public static string FAQ72 {
            get {
                return ResourceManager.GetString("FAQ72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any elimination rounds removing players from this shortlist during the duration of the global vote? .
        /// </summary>
        public static string FAQ73 {
            get {
                return ResourceManager.GetString("FAQ73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. You can choose from the full shortlist of 1100 players referenced above..
        /// </summary>
        public static string FAQ74 {
            get {
                return ResourceManager.GetString("FAQ74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. The aim of the game is to correctly predict the two squads for Europe and the Rest of the World with the highest votes by position. Being injured does not disqualify a player from being chosen in the final squad.  .
        /// </summary>
        public static string FAQ75 {
            get {
                return ResourceManager.GetString("FAQ75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any new players be added to this shortlist during the duration of the competition? .
        /// </summary>
        public static string FAQ76 {
            get {
                return ResourceManager.GetString("FAQ76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players will be added to this shortlist during the competition..
        /// </summary>
        public static string FAQ77 {
            get {
                return ResourceManager.GetString("FAQ77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any selection limitations? .
        /// </summary>
        public static string FAQ78 {
            get {
                return ResourceManager.GetString("FAQ78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no country, league or team limitations. Entrants are free to select any player from the shortlist..
        /// </summary>
        public static string FAQ79 {
            get {
                return ResourceManager.GetString("FAQ79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What formations can I choose? .
        /// </summary>
        public static string FAQ8 {
            get {
                return ResourceManager.GetString("FAQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What online payment system do you use? Is it secure?.
        /// </summary>
        public static string FAQ80 {
            get {
                return ResourceManager.GetString("FAQ80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any payment made online will be made through the Paypal payment system to guarantee your security or other payment providers. Please visit www.paypal.com for more information. Please note that currency exchange rates may vary from provider to provider.  For further information, please check with your provider..
        /// </summary>
        public static string FAQ81 {
            get {
                return ResourceManager.GetString("FAQ81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formation is set at a standard 4-4-2 only..
        /// </summary>
        public static string FAQ9 {
            get {
                return ResourceManager.GetString("FAQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for FAQs.
        /// </summary>
        public static string FAQButton {
            get {
                return ResourceManager.GetString("FAQButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQPageTitle {
            get {
                return ResourceManager.GetString("FAQPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is your favourite major league to watch?.
        /// </summary>
        public static string FavouriteLeague {
            get {
                return ResourceManager.GetString("FavouriteLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite League.
        /// </summary>
        public static string FavouriteLeaguePage {
            get {
                return ResourceManager.GetString("FavouriteLeaguePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your favourite major league.
        /// </summary>
        public static string FavouriteLeagueWatermark {
            get {
                return ResourceManager.GetString("FavouriteLeagueWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is your favourite player from the FAS 1100 list?.
        /// </summary>
        public static string FavouritePlayer {
            get {
                return ResourceManager.GetString("FavouritePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Player.
        /// </summary>
        public static string FavouritePlayerPage {
            get {
                return ResourceManager.GetString("FavouritePlayerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your favourite player.
        /// </summary>
        public static string FavouritePlayerWatermark {
            get {
                return ResourceManager.GetString("FavouritePlayerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select favourite club.
        /// </summary>
        public static string FavouritesPage {
            get {
                return ResourceManager.GetString("FavouritesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other than football, what is your favourite sport?.
        /// </summary>
        public static string FavouriteSport {
            get {
                return ResourceManager.GetString("FavouriteSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Sport.
        /// </summary>
        public static string FavouriteSportPage {
            get {
                return ResourceManager.GetString("FavouriteSportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your other favourite sport.
        /// </summary>
        public static string FavouriteSportWatermark {
            get {
                return ResourceManager.GetString("FavouriteSportWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your favourite football stadium in the world?.
        /// </summary>
        public static string FavouriteStadium {
            get {
                return ResourceManager.GetString("FavouriteStadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Stadium.
        /// </summary>
        public static string FavouriteStadiumPage {
            get {
                return ResourceManager.GetString("FavouriteStadiumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your favourite stadium.
        /// </summary>
        public static string FavouriteStadiumWatermark {
            get {
                return ResourceManager.GetString("FavouriteStadiumWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a first favourite team.
        /// </summary>
        public static string FavouriteTeam1 {
            get {
                return ResourceManager.GetString("FavouriteTeam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a second favourite team.
        /// </summary>
        public static string FavouriteTeam2 {
            get {
                return ResourceManager.GetString("FavouriteTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your first name.
        /// </summary>
        public static string FirstnameWatermark {
            get {
                return ResourceManager.GetString("FirstnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardName {
            get {
                return ResourceManager.GetString("ForwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Entry.
        /// </summary>
        public static string FreeEntry {
            get {
                return ResourceManager.GetString("FreeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full View.
        /// </summary>
        public static string FullViewPivot {
            get {
                return ResourceManager.GetString("FullViewPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goalkeeper.
        /// </summary>
        public static string GoalKeeperName {
            get {
                return ResourceManager.GetString("GoalKeeperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Player.
        /// </summary>
        public static string HelpChoosePlayer {
            get {
                return ResourceManager.GetString("HelpChoosePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll through all the players available for this position and choose one..
        /// </summary>
        public static string HelpChoosePlayerText {
            get {
                return ResourceManager.GetString("HelpChoosePlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string HelpNavigation {
            get {
                return ResourceManager.GetString("HelpNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe the home screen to see other pitch views.
        /// </summary>
        public static string HelpNavigationText {
            get {
                return ResourceManager.GetString("HelpNavigationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Another Game.
        /// </summary>
        public static string HelpNewGame {
            get {
                return ResourceManager.GetString("HelpNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can make another game by simply buying some more votes..
        /// </summary>
        public static string HelpNewGameText {
            get {
                return ResourceManager.GetString("HelpNewGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Page.
        /// </summary>
        public static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a position.
        /// </summary>
        public static string HelpPosition {
            get {
                return ResourceManager.GetString("HelpPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start filling all the players on the pitch by clicking a position.
        /// </summary>
        public static string HelpPositionText {
            get {
                return ResourceManager.GetString("HelpPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your Game.
        /// </summary>
        public static string HelpSubmit {
            get {
                return ResourceManager.GetString("HelpSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have picked your 30 (subs too) then submit your Game..
        /// </summary>
        public static string HelpSubmitText {
            get {
                return ResourceManager.GetString("HelpSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the Greatest team.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for the best players in each position for both Europe and the Rest of the World..
        /// </summary>
        public static string HelpVoteForBest {
            get {
                return ResourceManager.GetString("HelpVoteForBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last successfull update {0}.
        /// </summary>
        public static string LastVoteUpdate {
            get {
                return ResourceManager.GetString("LastVoteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string LaterButton {
            get {
                return ResourceManager.GetString("LaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Back.
        /// </summary>
        public static string LeftBackName {
            get {
                return ResourceManager.GetString("LeftBackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listing by club:.
        /// </summary>
        public static string ListingByClub {
            get {
                return ResourceManager.GetString("ListingByClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listing by country:.
        /// </summary>
        public static string ListingByCountry {
            get {
                return ResourceManager.GetString("ListingByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listing by position:.
        /// </summary>
        public static string ListingByPosition {
            get {
                return ResourceManager.GetString("ListingByPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out.
        /// </summary>
        public static string LoggedOutMessage {
            get {
                return ResourceManager.GetString("LoggedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your login details..
        /// </summary>
        public static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midfielder.
        /// </summary>
        public static string MidfieldName {
            get {
                return ResourceManager.GetString("MidfieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your mobile number.
        /// </summary>
        public static string MobileWatermark {
            get {
                return ResourceManager.GetString("MobileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the slider if you want to cast more than 1 vote:.
        /// </summary>
        public static string MoveSliderVoteText {
            get {
                return ResourceManager.GetString("MoveSliderVoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your country.
        /// </summary>
        public static string MyCountryPage {
            get {
                return ResourceManager.GetString("MyCountryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password has been emailed to you.
        /// </summary>
        public static string NewPasswordMessage {
            get {
                return ResourceManager.GetString("NewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose a new password.
        /// </summary>
        public static string NewPasswordWatermark {
            get {
                return ResourceManager.GetString("NewPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New votes have been added to your account.
        /// </summary>
        public static string NewVotesAdded {
            get {
                return ResourceManager.GetString("NewVotesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in on this phone.
        /// </summary>
        public static string NotLoggedInPopup {
            get {
                return ResourceManager.GetString("NotLoggedInPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough votes. Do you want to visit the shop?.
        /// </summary>
        public static string NoVotesMessage {
            get {
                return ResourceManager.GetString("NoVotesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough votes.
        /// </summary>
        public static string NoVotesTitle {
            get {
                return ResourceManager.GetString("NoVotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 6 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your registered email address and we will email you a new password..
        /// </summary>
        public static string PasswordResetDesc {
            get {
                return ResourceManager.GetString("PasswordResetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed.
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password and choose a new password..
        /// </summary>
        public static string PasswordUpdateText {
            get {
                return ResourceManager.GetString("PasswordUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose a password.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be taken to the paypal website to complete the transaction.
        /// </summary>
        public static string PayPalLink {
            get {
                return ResourceManager.GetString("PayPalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigation to paypal failed.
        /// </summary>
        public static string PayPalNavFailed {
            get {
                return ResourceManager.GetString("PayPalNavFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Payment.
        /// </summary>
        public static string PayPalTitle {
            get {
                return ResourceManager.GetString("PayPalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player culled.
        /// </summary>
        public static string PlayerCulled {
            get {
                return ResourceManager.GetString("PlayerCulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player moving values have been synced.
        /// </summary>
        public static string PlayerMoveSynced {
            get {
                return ResourceManager.GetString("PlayerMoveSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersTitle {
            get {
                return ResourceManager.GetString("PlayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to vote for the following player.
        /// </summary>
        public static string PlayerVoteText {
            get {
                return ResourceManager.GetString("PlayerVoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a position for this player:.
        /// </summary>
        public static string PositionSelectVote {
            get {
                return ResourceManager.GetString("PositionSelectVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the following position:.
        /// </summary>
        public static string PositionVoteText {
            get {
                return ResourceManager.GetString("PositionVoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans All Star.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged on to make purchases..
        /// </summary>
        public static string PurchaseLoginWarning {
            get {
                return ResourceManager.GetString("PurchaseLoginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my purchases.
        /// </summary>
        public static string PurchasesTitle {
            get {
                return ResourceManager.GetString("PurchasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your details and then press the tick button at the bottom.
        /// </summary>
        public static string RegistrationHelp {
            get {
                return ResourceManager.GetString("RegistrationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegistrationPage {
            get {
                return ResourceManager.GetString("RegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email failed.
        /// </summary>
        public static string ResendEmailFailed {
            get {
                return ResourceManager.GetString("ResendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resending Activation Email.
        /// </summary>
        public static string ResendEmailMessage {
            get {
                return ResourceManager.GetString("ResendEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want us to re-email your activation pin to your registered email address, please click the button below..
        /// </summary>
        public static string ResendPin {
            get {
                return ResourceManager.GetString("ResendPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend activation Pin.
        /// </summary>
        public static string ResendPinButton {
            get {
                return ResourceManager.GetString("ResendPinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your registered email address.
        /// </summary>
        public static string ResetEmailWatermark {
            get {
                return ResourceManager.GetString("ResetEmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset my password.
        /// </summary>
        public static string ResetMyPasswordLink {
            get {
                return ResourceManager.GetString("ResetMyPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want a password reset pin for a different account to above, please log out first..
        /// </summary>
        public static string ResetOtherDesc {
            get {
                return ResourceManager.GetString("ResetOtherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset password.
        /// </summary>
        public static string ResetPasswordPage {
            get {
                return ResourceManager.GetString("ResetPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Back.
        /// </summary>
        public static string RightBackName {
            get {
                return ResourceManager.GetString("RightBackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTW.
        /// </summary>
        public static string ROTWAbriviation {
            get {
                return ResourceManager.GetString("ROTWAbriviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest of the world.
        /// </summary>
        public static string ROTWName {
            get {
                return ResourceManager.GetString("ROTWName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all.
        /// </summary>
        public static string ShowAllApis {
            get {
                return ResourceManager.GetString("ShowAllApis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show where apis are needed.
        /// </summary>
        public static string ShowApisNeeded {
            get {
                return ResourceManager.GetString("ShowApisNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated vote {0} failed!.
        /// </summary>
        public static string SimulatedVoteFailed {
            get {
                return ResourceManager.GetString("SimulatedVoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated vote {0} has been cast!.
        /// </summary>
        public static string SimulatedVoteSuccessful {
            get {
                return ResourceManager.GetString("SimulatedVoteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Centre Back.
        /// </summary>
        public static string SubstituteDefenderName {
            get {
                return ResourceManager.GetString("SubstituteDefenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Forward.
        /// </summary>
        public static string SubstituteForwardName {
            get {
                return ResourceManager.GetString("SubstituteForwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Goalkeeper.
        /// </summary>
        public static string SubstituteKeeperName {
            get {
                return ResourceManager.GetString("SubstituteKeeperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Midfielder.
        /// </summary>
        public static string SubstituteMidfielderName {
            get {
                return ResourceManager.GetString("SubstituteMidfielderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your last name.
        /// </summary>
        public static string SurnameWatermark {
            get {
                return ResourceManager.GetString("SurnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and conditions.
        /// </summary>
        public static string TermsAccept {
            get {
                return ResourceManager.GetString("TermsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        public static string TermsURL {
            get {
                return ResourceManager.GetString("TermsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transactions have been synced.
        /// </summary>
        public static string TransactionSynced {
            get {
                return ResourceManager.GetString("TransactionSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have completed your transaction, your account will be credited with new votes within a few minutes. Press the back button below to go back to the main page..
        /// </summary>
        public static string TransactionUpdate {
            get {
                return ResourceManager.GetString("TransactionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Failed.
        /// </summary>
        public static string UpdateAccountFailed {
            get {
                return ResourceManager.GetString("UpdateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was successfully updated.
        /// </summary>
        public static string UpdateAccountSuccess {
            get {
                return ResourceManager.GetString("UpdateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesTitle {
            get {
                return ResourceManager.GetString("UpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Account.
        /// </summary>
        public static string UpdatingAccount {
            get {
                return ResourceManager.GetString("UpdatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote will be cast. But for your vote to be counted you must confirm your account by clicking on the link in the welcome email..
        /// </summary>
        public static string ValidateAccountMessage1 {
            get {
                return ResourceManager.GetString("ValidateAccountMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have confirmed in the last few minutes, please ignore this message..
        /// </summary>
        public static string ValidateAccountMessage2 {
            get {
                return ResourceManager.GetString("ValidateAccountMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently validated.
        /// </summary>
        public static string ValidateAccountTitle {
            get {
                return ResourceManager.GetString("ValidateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Confirm.
        /// </summary>
        public static string VoteConfirmTitle {
            get {
                return ResourceManager.GetString("VoteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Failed.
        /// </summary>
        public static string VoteFailed {
            get {
                return ResourceManager.GetString("VoteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged on to vote..
        /// </summary>
        public static string VoteLoginWarning {
            get {
                return ResourceManager.GetString("VoteLoginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your votes have been synced.
        /// </summary>
        public static string VotesSynced {
            get {
                return ResourceManager.GetString("VotesSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my votes.
        /// </summary>
        public static string VotesTitle {
            get {
                return ResourceManager.GetString("VotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote for {0} was submitted successfully.
        /// </summary>
        public static string VoteSuccessful {
            get {
                return ResourceManager.GetString("VoteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
